# File: docker-compose.yaml
version: '3.9'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
    command: "--jetstream"
    volumes:
      - nats-data:/data
    environment:
      - NATS_SERVER_NAME=observability-agent-nats

  orchestrator:
    build: ./orchestrator
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}

  observability_agent:
    build: ./agents/observability_agent
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - PROMETHEUS_URL=${PROMETHEUS_URL:-http://prometheus:9090}
      - LOKI_URL=${LOKI_URL:-http://loki:3100}
      - TEMPO_URL=${TEMPO_URL:-http://tempo:3200}

  infrastructure_agent:
    build: ./agents/infrastructure_agent
    depends_on:
      - nats
    volumes:
      - ${HOME}/.kube:/root/.kube:ro
    environment:
      - NATS_URL=nats://nats:4222
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - KUBECONFIG=/root/.kube/config
      - ARGOCD_SERVER=${ARGOCD_SERVER:-https://argocd-server.argocd:443}

  communication_agent:
    build: ./agents/communication_agent
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - WEBEX_BOT_TOKEN=${WEBEX_BOT_TOKEN:-}
      - PAGERDUTY_INTEGRATION_KEY=${PAGERDUTY_INTEGRATION_KEY:-}

  root_cause_agent:
    build: ./agents/root_cause_agent
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}

  unified_backend:
    build: ./ui/unified-backend
    ports:
      - "5000:5000"
    depends_on:
      - nats
    volumes:
      - ${HOME}/.kube:/root/.kube:ro
    environment:
      - NATS_URL=nats://nats:4222
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KUBECONFIG=/root/.kube/config
      - PORT=5000
      - CACHE_TTL=300000

  ui:
    build: ./ui
    ports:
      - "8080:80"
    depends_on:
      - orchestrator
      - unified_backend
    environment:
      - BACKEND_SERVICE_URL=http://unified_backend:5000

volumes:
  nats-data: