version: '3'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
    command: "--jetstream --js_domain observability-agent"
    volumes:
      - nats-data:/data
    environment:
      - NATS_SERVER_NAME=local-nats

volumes:
  nats-data: