apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-agent.fullname" . }}-nats
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: client
      protocol: TCP
      name: client
    - port: 8222
      targetPort: monitor
      protocol: TCP
      name: monitor
    - port: 6222
      targetPort: cluster
      protocol: TCP
      name: cluster
  selector:
    {{- include "observability-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats