apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-agent.fullname" . }}-nats-config
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
data:
  nats.conf: |
    # Basic NATS configuration
    http_port: 8222

    # JetStream configuration
    {{- if .Values.nats.jetstream.enabled }}
    jetstream {
      {{- if .Values.nats.persistence.enabled }}
      # File-based storage
      store_dir: /data
      {{- else }}
      # Memory-based storage
      max_mem: {{ .Values.nats.persistence.memStorage | default "1G" }}
      {{- end }}
    }
    {{- end }}

  js-streams.json: |
    {
      "streams": [
        {
          "name": "ALERTS",
          "subjects": ["alerts", "alerts.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "AGENT_TASKS",
          "subjects": ["metric_agent", "log_agent", "deployment_agent", "tracing_agent", 
                      "root_cause_agent", "notification_agent", "postmortem_agent", "runbook_agent",
                      "agent.tasks.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "AGENTS",
          "subjects": ["agent.status.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "RESPONSES",
          "subjects": ["orchestrator_response", "responses.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "ALERT_DATA",
          "subjects": ["alert_data_request", "alert_data_response.*", "alert.data.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "ROOT_CAUSE",
          "subjects": ["root_cause_analysis", "root_cause_result", "rootcause.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "NOTIFICATIONS",
          "subjects": ["notification_requests", "notifications."],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "METRICS",
          "subjects": ["metrics", "metrics.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "LOGS",
          "subjects": ['logs", "logs.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "DEPLOYMENTS",
          "subjects": ["deployments", "deployments.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "TRACES",
          "subjects": ["traces", "traces.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "POSTMORTEMS",
          "subjects": ["postmortems", "postmortems.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "RUNBOOKS",
          "subjects": ["runbooks", "runbook.definition.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "RUNBOOK_EXECUTIONS",
          "subjects": ["runbook.execute", "runbook.status.>", "runbook.execution.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        },
        {
          "name": "NOTEBOOKS",
          "subjects": ["notebooks", "notebooks.>"],
          "retention": "limits",
          "max_msgs": 10000,
          "max_bytes": 104857600,
          "max_age": 604800000000000,
          "storage": "file",
          "discard": "old"
        }
      ]
    }
