{{- if and .Values.nats.enabled .Values.nats.jetstream.enabled .Values.nats.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability-agent.fullname" . }}-nats-data
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nats.persistence.size }}
  {{- if .Values.nats.persistence.storageClass }}
  {{- if (eq "-" .Values.nats.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.nats.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}