apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-agent.fullname" . }}-openai
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
data:
  OPENAI_API_KEY: "{{ .Values.openai.apiKey }}"
  OPENAI_MODEL: "{{ .Values.openai.model | default "gpt-4" }}"