apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-agent.fullname" . }}-openai
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.openai.apiKey | b64enc | quote }}