apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-agent.fullname" . }}-orchestrator
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicas }}
  selector:
    matchLabels:
      {{- include "observability-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      labels:
        {{- include "observability-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "observability-agent.fullname" . }}-openai
                  key: api_key
            - name: OPENAI_MODEL
              value: {{ .Values.openai.model | default "gpt-4" | quote }}
            - name: NATS_URL
              value: "nats://{{ include "observability-agent.fullname" . }}-nats:4222"
            # Add environment variables to specify which agents are available
            - name: METRIC_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.metric }}"
            - name: LOG_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.log }}"
            - name: DEPLOYMENT_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.deployment }}"
            - name: TRACING_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.tracing }}"
            - name: ROOT_CAUSE_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.rootCause }}"
            - name: RUNBOOK_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.runbook }}"
            - name: NOTIFICATION_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.notification }}"
            - name: POSTMORTEM_AGENT_ENABLED
              value: "{{ .Values.agents.enabled.postmortem }}"
            {{- range .Values.agents.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.orchestrator.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}